;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


songs_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,389,324 ; title
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,225,187 ; gravity
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,299,249 ; sewer

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env16
	.word @env3,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env16
	.word @env4,@env0,@env0,@env0
	.word @env2,@env9,@env0,@env18
	.word @env2,@env0,@env0,@env19
	.word @env3,@env0,@env0,@env16
	.word @env4,@env0,@env0,@env17
	.word @env1,@env0,@env0,@env17
	.word @env2,@env0,@env0,@env16
	.word @env2,@env11,@env0,@env18
	.word @env5,@env0,@env0,@env17
	.word @env7,@env0,@env0,@env0
	.word @env2,@env10,@env0,@env0
	.word @env8,@env0,@env0,@env0
	.word @env6,@env12,@env0,@env0
	.word @env6,@env13,@env0,@env0
	.word @env2,@env0,@env0,@env16
	.word @env2,@env14,@env0,@env0
	.word @env4,@env0,@env0,@env17
	.word @env8,@env0,@env0,@env18
	.word @env6,@env15,@env0,@env0
	.word @env2,@env13,@env0,@env16
	.word @env2,@env12,@env0,@env16

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$02,$c4
	.byte $c4,$c3,$02,$c2,$02,$c1,$04,$c0,$c0,$c0,$00,$19
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cc,$ca,$c8,$c6,$ca,$c7,$c5,$c4,$c3,$c2,$c1,$c0,$c0,$00,$0c
@env4:
	.byte $cf,$cb,$c6,$c2,$c0,$00,$04
@env5:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$02
	.byte $c4,$03,$c3,$04,$c2,$05,$c1,$08,$c1,$00,$18
@env6:
	.byte $cf,$cb,$c8,$c6,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$c0,$c0,$00
	.byte $0e
@env7:
	.byte $cf,$c5,$c0,$00,$02
@env8:
	.byte $c4,$c7,$c9,$c7,$c4,$c0,$c1,$c3,$c4,$c3,$c1,$c0,$c0,$00,$0c
@env9:
	.byte $d8,$d8,$d3,$d3,$d0,$d0,$ce,$ce,$cc,$cc,$c7,$c7,$c4,$c4,$c2,$c2
	.byte $c0,$c0,$00,$00
@env10:
	.byte $cc,$c0,$00,$01
@env11:
	.byte $d8,$d8,$d3,$d3,$cf,$cf,$ce,$ce,$cc,$cc,$c7,$c7,$c3,$c3,$c2,$c2
	.byte $c0,$c0,$00,$00
@env12:
	.byte $c0,$c4,$c7,$00,$00
@env13:
	.byte $c0,$c3,$c7,$00,$00
@env14:
	.byte $c0,$c5,$c7,$00,$00
@env15:
	.byte $c0,$c3,$c6,$00,$00
@env16:
	.byte $c2,$00,$00
@env17:
	.byte $c1,$00,$00
@env18:
	.byte $c2,$c1,$c3,$00,$02
@env19:
	.byte $c3,$00,$00


; title
@song0ch0:
	.byte $fb,$02
@ref0:
	.byte $8f
@ref1:
	.byte $8f
@song0ch0loop:
@ref2:
	.byte $76,$82,$04,$ad,$6c,$0a,$8f
@ref3:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$85,$00,$85
@ref4:
	.byte $76,$04,$85,$00,$85,$04,$ad
@ref5:
	.byte $6c,$0a,$8f,$5f,$00,$9d,$04,$83,$00,$04,$83,$00
@ref6:
	.byte $76,$04,$ad,$6c,$0a,$8f
@ref7:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$83,$00,$04,$83,$00
	.byte $ff,$06
	.word @ref4
@ref9:
	.byte $6c,$0a,$8f,$5f,$00,$8d,$0b,$9d
	.byte $ff,$03
	.word @ref6
@ref11:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$83,$00,$76,$04,$83,$00
@ref12:
	.byte $76,$04,$85,$00,$85,$76,$04,$9b,$00,$04,$8b,$00
@ref13:
	.byte $03,$b3,$00,$03,$83,$00
@ref14:
	.byte $76,$01,$9d,$0d,$9d
@ref15:
	.byte $09,$9d,$10,$9d
@ref16:
	.byte $76,$0e,$85,$00,$85,$0e,$9d,$09,$8d
@ref17:
	.byte $06,$9b,$00,$02,$9d
@ref18:
	.byte $78,$8c,$1f,$8f,$72,$8d,$7a,$8e,$18,$19,$1a,$99
@ref19:
	.byte $1f,$95,$6c,$09,$85,$00,$5f,$25,$26,$99,$00
@ref20:
	.byte $7a,$25,$9d,$66,$8d,$00,$60,$21,$8b,$00
@ref21:
	.byte $60,$1f,$20,$21,$b7,$00
@ref22:
	.byte $77,$8c,$1f,$8f,$72,$8d,$7a,$8e,$18,$19,$1a,$8d,$1c,$81,$1a,$81
	.byte $19,$81
@ref23:
	.byte $1f,$95,$6c,$04,$85,$00,$5f,$22,$23,$99,$00
@ref24:
	.byte $7a,$21,$85,$1c,$83,$00,$1c,$ad
@ref25:
	.byte $66,$9d,$60,$00,$74,$90,$31,$85,$75,$32,$85,$76,$34,$85,$77,$39
	.byte $83,$00
	.byte $ff,$0d
	.word @ref22
@ref27:
	.byte $1f,$95,$6c,$04,$85,$00,$5f,$25,$26,$99,$00
@ref28:
	.byte $25,$85,$26,$83,$00,$28,$8d,$66,$8d,$60,$00,$26,$85,$25,$83,$00
@ref29:
	.byte $26,$9d,$66,$8d,$60,$00,$21,$85,$23,$83,$00
@ref30:
	.byte $24,$9d,$66,$8d,$60,$00,$26,$85,$24,$83,$00
@ref31:
	.byte $23,$9d,$6d,$17,$1f,$9d
@ref32:
	.byte $23,$bd
@ref33:
	.byte $66,$9f,$60,$00,$83,$00,$76,$5f,$82,$01,$83,$00,$02,$83,$00,$03
	.byte $83,$00
	.byte $fd
	.word @song0ch0loop

; title
@song0ch1:
@ref34:
	.byte $8f
@ref35:
	.byte $8f
@song0ch1loop:
@ref36:
	.byte $78,$86,$28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85
	.byte $1e,$85
@ref37:
	.byte $28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85,$1e,$85
@ref38:
	.byte $79,$2a,$85,$25,$85,$22,$85,$20,$85,$2a,$85,$25,$85,$22,$85,$20
	.byte $85
@ref39:
	.byte $12,$85,$16,$85,$19,$85,$16,$85,$19,$85,$1e,$85,$22,$85,$25,$85
@ref40:
	.byte $79,$28,$85,$25,$85,$23,$85,$21,$85,$2d,$85,$28,$85,$25,$85,$21
	.byte $85
@ref41:
	.byte $28,$85,$24,$85,$23,$85,$21,$85,$28,$85,$24,$85,$23,$85,$21,$85
@ref42:
	.byte $79,$28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85,$1e
	.byte $85
@ref43:
	.byte $10,$85,$14,$85,$17,$85,$1c,$85,$17,$85,$1c,$85,$20,$85,$23,$85
	.byte $ff,$10
	.word @ref42
	.byte $ff,$10
	.word @ref37
@ref46:
	.byte $79,$2a,$85,$28,$85,$22,$85,$1e,$85,$2a,$85,$28,$85,$22,$85,$1e
	.byte $85
@ref47:
	.byte $2a,$85,$25,$85,$23,$85,$1e,$85,$2f,$85,$2a,$85,$27,$85,$23,$85
@ref48:
	.byte $79,$28,$85,$25,$85,$23,$85,$21,$85,$28,$85,$25,$85,$23,$85,$21
	.byte $85
@ref49:
	.byte $31,$85,$2f,$85,$2d,$85,$28,$85,$34,$85,$31,$85,$2f,$85,$2d,$85
@ref50:
	.byte $79,$36,$85,$34,$85,$32,$85,$2d,$85,$36,$85,$34,$85,$32,$85,$2d
	.byte $85
@ref51:
	.byte $32,$85,$2d,$85,$2a,$85,$2d,$85,$2a,$85,$26,$85,$2a,$85,$2d,$85
@ref52:
	.byte $79,$2f,$85,$2d,$85,$2b,$85,$26,$85,$90,$2f,$85,$2d,$85,$2b,$85
	.byte $26,$85
@ref53:
	.byte $86,$2f,$85,$2d,$85,$2b,$85,$26,$85,$90,$2f,$85,$2d,$85,$2b,$85
	.byte $26,$85
@ref54:
	.byte $79,$86,$31,$85,$2f,$85,$2d,$85,$28,$85,$90,$31,$85,$2f,$85,$2d
	.byte $85,$28,$85
@ref55:
	.byte $86,$31,$85,$2f,$85,$2d,$85,$28,$85,$90,$31,$85,$2f,$85,$2d,$85
	.byte $28,$85
@ref56:
	.byte $79,$86,$2f,$85,$2d,$85,$2b,$85,$26,$85,$90,$2f,$85,$2d,$85,$2b
	.byte $85,$26,$85
	.byte $ff,$10
	.word @ref53
@ref58:
	.byte $79,$86,$28,$85,$25,$85,$23,$85,$1c,$85,$90,$31,$85,$2f,$85,$2d
	.byte $85,$28,$85
@ref59:
	.byte $86,$25,$85,$28,$85,$2d,$85,$28,$85,$90,$2d,$85,$2f,$85,$31,$85
	.byte $34,$85
	.byte $ff,$10
	.word @ref56
	.byte $ff,$10
	.word @ref53
	.byte $ff,$10
	.word @ref54
@ref63:
	.byte $86,$32,$85,$2d,$85,$2a,$85,$28,$85,$26,$85,$21,$85,$26,$85,$90
	.byte $26,$85
@ref64:
	.byte $79,$86,$2b,$85,$28,$85,$24,$85,$1f,$85,$90,$28,$85,$24,$85,$1f
	.byte $85,$1c,$85
@ref65:
	.byte $79,$86,$2b,$85,$26,$85,$23,$85,$1f,$85,$90,$26,$85,$23,$85,$1f
	.byte $85,$1a,$85
@ref66:
	.byte $79,$86,$28,$85,$25,$85,$23,$85,$1e,$85,$79,$28,$85,$25,$85,$23
	.byte $85,$1e,$85
@ref67:
	.byte $79,$28,$85,$25,$85,$23,$85,$1e,$85,$2a,$85,$27,$85,$23,$85,$21
	.byte $85
	.byte $fd
	.word @song0ch1loop

; title
@song0ch2:
@ref68:
	.byte $8f
@ref69:
	.byte $8f
@song0ch2loop:
@ref70:
	.byte $9f,$84,$2d,$2e,$2f,$97,$00
@ref71:
	.byte $34,$95,$6c,$04,$85,$00,$5f,$3a,$3b,$99,$00
@ref72:
	.byte $3a,$bd
@ref73:
	.byte $63,$9f,$60,$00,$8d,$36,$85,$38,$83,$00
@ref74:
	.byte $39,$9d,$63,$9d,$00
@ref75:
	.byte $60,$3b,$9d,$63,$97,$60,$39,$83,$00
@ref76:
	.byte $38,$85,$36,$83,$00,$34,$9d,$63,$8f
@ref77:
	.byte $8f,$60,$00,$ad
@ref78:
	.byte $9f,$2d,$2e,$2f,$8d,$31,$81,$2f,$81,$2e,$81
	.byte $ff,$08
	.word @ref71
@ref80:
	.byte $3d,$9d,$63,$8d,$60,$00,$3b,$85,$3a,$83,$00
@ref81:
	.byte $3b,$9d,$00,$8d,$36,$85,$38,$83,$00
@ref82:
	.byte $39,$9d,$63,$8d,$00,$60,$38,$85,$36,$83,$00
@ref83:
	.byte $34,$95,$6c,$05,$87,$5f,$31,$8d,$36,$8d
@ref84:
	.byte $36,$bd
@ref85:
	.byte $63,$9f,$60,$00,$9d
@ref86:
	.byte $82,$13,$85,$00,$85,$13,$85,$00,$a5
@ref87:
	.byte $8f,$13,$8d,$00,$8d,$13,$83,$00,$13,$83,$00
@ref88:
	.byte $13,$85,$00,$85,$13,$85,$00,$a5
@ref89:
	.byte $97,$96,$00,$85,$82,$0e,$95,$96,$00,$85
	.byte $ff,$08
	.word @ref86
	.byte $ff,$0b
	.word @ref87
	.byte $ff,$08
	.word @ref88
@ref93:
	.byte $8f,$0e,$8d,$00,$8d,$0e,$8d
	.byte $ff,$08
	.word @ref88
	.byte $ff,$0b
	.word @ref87
@ref96:
	.byte $15,$9d,$6d,$20,$21,$9d
@ref97:
	.byte $5f,$1e,$9d,$0e,$9b,$00
@ref98:
	.byte $10,$bd
@ref99:
	.byte $5f,$13,$9d,$5f,$1a,$9b,$00
@ref100:
	.byte $1e,$ab,$00,$90,$19,$83,$00,$17,$83,$00
@ref101:
	.byte $82,$12,$9b,$00,$17,$9b,$00
	.byte $fd
	.word @song0ch2loop

; title
@song0ch3:
@ref102:
	.byte $74,$80,$0c,$85,$76,$0a,$85
@ref103:
	.byte $78,$07,$85,$7a,$05,$85
@song0ch3loop:
@ref104:
	.byte $76,$82,$0a,$85,$75,$87,$74,$85,$72,$85,$71,$83,$00,$8d,$73,$8a
	.byte $0e,$81,$74,$0e,$81,$75,$0e,$81,$76,$0e,$81
@ref105:
	.byte $77,$80,$06,$75,$81,$73,$81,$71,$81,$00,$85,$73,$82,$06,$85,$72
	.byte $87,$71,$81,$00,$8b,$75,$8a,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78
	.byte $0e,$81
@ref106:
	.byte $77,$0e,$85,$74,$0e,$85,$75,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$85,$74,$0e,$85
@ref107:
	.byte $78,$82,$0f,$85,$75,$87,$72,$83,$71,$83,$72,$8a,$0e,$85,$74,$80
	.byte $0c,$85,$74,$0a,$85,$74,$08,$85,$74,$07,$85
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
@ref120:
	.byte $7a,$92,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85
	.byte $74,$0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
@ref121:
	.byte $7a,$8a,$06,$78,$81,$76,$81,$73,$81,$00,$85,$7a,$0f,$85,$78,$87
	.byte $77,$92,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85
@ref122:
	.byte $7a,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
@ref126:
	.byte $77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
@ref127:
	.byte $7a,$8a,$06,$78,$81,$76,$81,$73,$81,$00,$85,$75,$92,$0e,$81,$76
	.byte $0e,$81,$77,$0e,$81,$78,$0e,$81,$7a,$8a,$06,$78,$81,$76,$81,$73
	.byte $81,$74,$92,$0e,$85,$7a,$0f,$85,$78,$87
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref126
@ref135:
	.byte $7a,$06,$78,$81,$76,$81,$73,$81,$00,$85,$7a,$0f,$85,$78,$87,$72
	.byte $80,$0c,$85,$73,$0a,$85,$74,$07,$85,$77,$05,$85
	.byte $fd
	.word @song0ch3loop

; title
@song0ch4:
@ref136:
	.byte $8f
@ref137:
	.byte $8f
@song0ch4loop:
@ref138:
	.byte $bf
@ref139:
	.byte $bf
@ref140:
	.byte $bf
@ref141:
	.byte $bf
@ref142:
	.byte $bf
@ref143:
	.byte $bf
@ref144:
	.byte $bf
@ref145:
	.byte $bf
@ref146:
	.byte $bf
@ref147:
	.byte $bf
@ref148:
	.byte $bf
@ref149:
	.byte $bf
@ref150:
	.byte $bf
@ref151:
	.byte $bf
@ref152:
	.byte $bf
@ref153:
	.byte $bf
@ref154:
	.byte $bf
@ref155:
	.byte $bf
@ref156:
	.byte $bf
@ref157:
	.byte $bf
@ref158:
	.byte $bf
@ref159:
	.byte $bf
@ref160:
	.byte $bf
@ref161:
	.byte $bf
@ref162:
	.byte $bf
@ref163:
	.byte $bf
@ref164:
	.byte $bf
@ref165:
	.byte $bf
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@ref168:
	.byte $bf
@ref169:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; gravity
@song1ch0:
	.byte $fb,$03
@song1ch0loop:
@ref170:
	.byte $bf
@ref171:
	.byte $bf
@ref172:
	.byte $71,$5f,$a6,$25,$72,$26,$73,$27,$74,$99,$66,$97,$73,$81,$72,$81
	.byte $71,$81,$70,$60,$81
@ref173:
	.byte $8f,$74,$25,$85,$2a,$95,$73,$6c,$02,$81,$72,$81,$71,$81,$70,$81
	.byte $74,$5f,$22,$81,$23,$81
@ref174:
	.byte $74,$22,$9d,$66,$97,$73,$81,$72,$81,$71,$81,$70,$60,$81
@ref175:
	.byte $8f,$71,$20,$72,$81,$73,$81,$74,$81,$25,$95,$27,$85,$73,$6c,$02
	.byte $81,$73,$81,$72,$81,$71,$81
@ref176:
	.byte $71,$5f,$25,$72,$26,$73,$27,$74,$99,$66,$97,$73,$81,$72,$81,$71
	.byte $81,$70,$60,$81
@ref177:
	.byte $97,$71,$60,$2e,$72,$81,$73,$2f,$74,$81,$2e,$85,$27,$85,$6d,$10
	.byte $2c,$85,$2a,$85
@ref178:
	.byte $9f,$66,$81,$5f,$95,$73,$81,$72,$81,$71,$81,$70,$60,$81
@ref179:
	.byte $bf
@ref180:
	.byte $bf
@ref181:
	.byte $9f,$78,$a0,$2f,$85,$2e,$85,$2a,$85,$27,$85
@ref182:
	.byte $bf
@ref183:
	.byte $9f,$78,$2f,$85,$2e,$85,$2a,$85,$27,$85
@ref184:
	.byte $bf
	.byte $ff,$09
	.word @ref183
@ref186:
	.byte $bf
	.byte $ff,$09
	.word @ref183
@ref188:
	.byte $bf
@ref189:
	.byte $bf
@ref190:
	.byte $bf
	.byte $fd
	.word @song1ch0loop

; gravity
@song1ch1:
@song1ch1loop:
@ref191:
	.byte $74,$9a,$14,$81,$72,$1b,$81,$74,$1b,$81,$72,$9e,$14,$81,$74,$9a
	.byte $22,$81,$72,$9e,$1b,$81,$74,$9a,$25,$81,$72,$9e,$22,$81,$74,$9a
	.byte $2a,$81,$72,$9e,$25,$81,$74,$9a,$25,$81,$72,$9e,$2a,$81,$74,$9a
	.byte $22,$81,$72,$9e,$25,$81,$74,$9a,$1b,$81,$72,$9e,$22,$81
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
@ref203:
	.byte $73,$8c,$28,$89,$72,$8b,$71,$8d,$00,$71,$b0,$20,$83,$00,$87,$20
	.byte $83,$00
@ref204:
	.byte $bf
@ref205:
	.byte $73,$8c,$27,$89,$72,$8b,$71,$8d,$00,$71,$b2,$1b,$83,$00,$87,$1b
	.byte $83,$00
@ref206:
	.byte $bf
@ref207:
	.byte $73,$98,$25,$89,$72,$8b,$71,$8d,$00,$71,$b0,$19,$83,$00,$87,$19
	.byte $83,$00
@ref208:
	.byte $bf
@ref209:
	.byte $74,$8c,$20,$89,$73,$8b,$72,$87,$71,$85,$00,$b2,$20,$83,$00,$87
	.byte $b0,$20,$83,$00
	.byte $ff,$20
	.word @ref191
	.byte $ff,$20
	.word @ref191
	.byte $fd
	.word @song1ch1loop

; gravity
@song1ch2:
@song1ch2loop:
@ref212:
	.byte $5f,$00,$bd
@ref213:
	.byte $5f,$00,$bd
@ref214:
	.byte $6d,$20,$82,$1c,$ad,$6c,$02,$8f
@ref215:
	.byte $6c,$60,$28,$5f,$19,$81,$00,$6c,$60,$28,$5f,$19,$81,$00,$8f,$6c
	.byte $60,$28,$5f,$1b,$81,$00,$6c,$60,$28,$5f,$1b,$81,$00,$8f
@ref216:
	.byte $14,$6d,$20,$20,$a3,$6c,$02,$97
@ref217:
	.byte $6c,$60,$28,$5f,$14,$81,$00,$6c,$60,$28,$5f,$14,$83,$00,$8d,$6c
	.byte $60,$28,$5f,$12,$81,$00,$6c,$60,$28,$5f,$12,$81,$00,$8f
@ref218:
	.byte $6d,$20,$19,$ad,$6c,$02,$8f
@ref219:
	.byte $6c,$60,$28,$5f,$1b,$81,$00,$6c,$60,$28,$5f,$1b,$81,$00,$8f,$6c
	.byte $60,$28,$5f,$1b,$81,$00,$6c,$60,$28,$5f,$1b,$81,$00,$8f
@ref220:
	.byte $6d,$20,$1c,$ad,$6c,$02,$8f
@ref221:
	.byte $6c,$60,$28,$5f,$1e,$81,$00,$6c,$60,$28,$5f,$1e,$81,$00,$8f,$6c
	.byte $60,$28,$5f,$12,$8b,$6c,$60,$28,$5f,$12,$83,$6b,$07,$87
@ref222:
	.byte $5f,$00,$bd
@ref223:
	.byte $5f,$00,$bd
@ref224:
	.byte $6c,$60,$28,$5f,$10,$81,$00,$6c,$60,$28,$5f,$10,$83,$00,$95,$6c
	.byte $60,$28,$00,$93
@ref225:
	.byte $5f,$00,$bd
@ref226:
	.byte $6c,$60,$28,$5f,$0f,$81,$00,$6c,$60,$28,$5f,$0f,$83,$00,$ad
@ref227:
	.byte $5f,$00,$bd
@ref228:
	.byte $6c,$60,$28,$5f,$0d,$81,$00,$6c,$60,$28,$5f,$0d,$83,$00,$ad
@ref229:
	.byte $5f,$00,$bd
@ref230:
	.byte $6c,$60,$28,$5f,$08,$81,$00,$6c,$60,$28,$5f,$08,$83,$00,$ad
@ref231:
	.byte $5f,$00,$bd
@ref232:
	.byte $5f,$00,$bd
	.byte $fd
	.word @song1ch2loop

; gravity
@song1ch3:
@song1ch3loop:
@ref233:
	.byte $bf
@ref234:
	.byte $bf
@ref235:
	.byte $bf
@ref236:
	.byte $bf
@ref237:
	.byte $bf
@ref238:
	.byte $bf
@ref239:
	.byte $bf
@ref240:
	.byte $bf
@ref241:
	.byte $bf
@ref242:
	.byte $bf
@ref243:
	.byte $bf
@ref244:
	.byte $bf
@ref245:
	.byte $72,$8a,$0c,$81,$72,$9c,$0c,$81,$72,$88,$0c,$85,$74,$82,$06,$73
	.byte $81,$72,$81,$71,$81,$70,$87,$72,$9c,$0c,$8d,$74,$82,$06,$73,$81
	.byte $72,$81,$71,$81,$72,$9c,$0c,$81,$72,$0c,$81
	.byte $ff,$15
	.word @ref245
	.byte $ff,$15
	.word @ref245
	.byte $ff,$15
	.word @ref245
	.byte $ff,$15
	.word @ref245
	.byte $ff,$15
	.word @ref245
@ref251:
	.byte $72,$8a,$0c,$85,$72,$9c,$0c,$85,$74,$82,$06,$73,$81,$72,$81,$71
	.byte $81,$70,$87,$72,$9c,$0c,$8d,$72,$0c,$81,$09,$81,$74,$8a,$08,$81
	.byte $88,$05,$81
@ref252:
	.byte $bf
@ref253:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

; gravity
@song1ch4:
@song1ch4loop:
@ref254:
	.byte $bf
@ref255:
	.byte $bf
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
@ref260:
	.byte $bf
@ref261:
	.byte $bf
@ref262:
	.byte $bf
@ref263:
	.byte $bf
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
@ref270:
	.byte $bf
@ref271:
	.byte $bf
@ref272:
	.byte $bf
@ref273:
	.byte $bf
@ref274:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


; sewer
@song2ch0:
	.byte $fb,$03
@song2ch0loop:
@ref275:
	.byte $8f,$76,$a0,$2d,$85,$25,$95,$ac,$2d,$85,$25,$85
@ref276:
	.byte $8f,$a0,$2d,$85,$25,$95,$ac,$2d,$85,$25,$85
@ref277:
	.byte $8f,$76,$a0,$30,$85,$27,$95,$ac,$30,$85,$27,$85
@ref278:
	.byte $8f,$a0,$2f,$85,$26,$95,$ac,$31,$85,$25,$85
	.byte $ff,$09
	.word @ref275
	.byte $ff,$09
	.word @ref276
	.byte $ff,$09
	.word @ref277
	.byte $ff,$09
	.word @ref278
@ref283:
	.byte $79,$aa,$24,$25,$83,$25,$85,$25,$85,$25,$85,$21,$85,$1c,$8d,$25
	.byte $85
@ref284:
	.byte $97,$1c,$85,$21,$85,$24,$25,$83,$00,$85,$24,$85
@ref285:
	.byte $76,$a0,$24,$85,$20,$85,$1b,$85,$24,$85,$20,$85,$1b,$85,$24,$85
	.byte $20,$85
@ref286:
	.byte $79,$aa,$23,$85,$25,$85,$23,$8d,$21,$8d,$20,$8d
@ref287:
	.byte $76,$24,$25,$83,$25,$85,$25,$85,$25,$85,$21,$85,$1c,$8d,$25,$85
@ref288:
	.byte $97,$1c,$85,$21,$85,$24,$25,$83,$00,$85,$27,$85
	.byte $ff,$10
	.word @ref285
@ref290:
	.byte $79,$8a,$28,$29,$8b,$23,$8d,$25,$85,$21,$85,$20,$8d
@ref291:
	.byte $7a,$1e,$8d,$78,$1e,$8d,$74,$1e,$8d,$72,$1e,$8d
@ref292:
	.byte $bf
	.byte $fd
	.word @song2ch0loop

; sewer
@song2ch1:
@song2ch1loop:
@ref293:
	.byte $8f,$78,$a4,$1e,$81,$00,$99,$1e,$8d
@ref294:
	.byte $8f,$1e,$81,$00,$99,$1e,$81,$00,$89
@ref295:
	.byte $8f,$78,$a2,$20,$81,$00,$99,$20,$8d
@ref296:
	.byte $8f,$1f,$81,$00,$99,$1f,$81,$00,$89
	.byte $ff,$07
	.word @ref293
	.byte $ff,$09
	.word @ref294
	.byte $ff,$07
	.word @ref295
@ref300:
	.byte $8f,$ae,$20,$81,$00,$99,$23,$81,$00,$89
@ref301:
	.byte $8f,$78,$a2,$21,$81,$00,$99,$21,$8d
@ref302:
	.byte $8f,$21,$81,$00,$99,$21,$81,$00,$89
@ref303:
	.byte $8f,$78,$20,$81,$00,$99,$20,$8d
	.byte $ff,$09
	.word @ref296
@ref305:
	.byte $8f,$78,$21,$81,$00,$99,$21,$8d
	.byte $ff,$09
	.word @ref302
	.byte $ff,$07
	.word @ref303
	.byte $ff,$09
	.word @ref300
@ref309:
	.byte $74,$82,$06,$85,$00,$85,$06,$85,$00,$85,$01,$85,$04,$85,$00,$85
	.byte $06,$85
@ref310:
	.byte $00,$bd
	.byte $fd
	.word @song2ch1loop

; sewer
@song2ch2:
@song2ch2loop:
@ref311:
	.byte $6c,$60,$82,$28,$5f,$12,$83,$00,$85,$6c,$60,$28,$5f,$12,$83,$00
	.byte $85,$6c,$60,$28,$5f,$0d,$83,$6c,$60,$28,$5f,$10,$83,$00,$83,$00
	.byte $6c,$60,$28,$5f,$12,$83
@ref312:
	.byte $6c,$30,$87,$00,$8d,$6c,$60,$28,$5f,$06,$83,$6c,$60,$28,$5f,$12
	.byte $83,$6c,$60,$28,$5f,$0d,$83,$5f,$00,$85,$6c,$60,$28,$5f,$0c,$83
@ref313:
	.byte $00,$ad,$00,$8b,$00
@ref314:
	.byte $6c,$60,$28,$5f,$0b,$8b,$6c,$60,$28,$5f,$17,$83,$6c,$30,$87,$6c
	.byte $60,$28,$5f,$18,$8b,$6c,$60,$28,$5f,$13,$8b
@ref315:
	.byte $6c,$60,$28,$5f,$12,$83,$00,$85,$6c,$60,$28,$5f,$12,$83,$00,$85
	.byte $6c,$60,$28,$5f,$0d,$83,$6c,$60,$28,$5f,$10,$83,$00,$83,$00,$6c
	.byte $60,$28,$5f,$12,$83
	.byte $ff,$11
	.word @ref312
	.byte $ff,$05
	.word @ref313
@ref318:
	.byte $6c,$60,$28,$5f,$0b,$8b,$6c,$60,$28,$5f,$17,$83,$6c,$30,$87,$6c
	.byte $60,$28,$5f,$19,$8b,$6c,$60,$28,$5f,$10,$83,$6b,$20,$87
@ref319:
	.byte $6c,$60,$28,$5f,$15,$83,$00,$85,$6c,$60,$28,$5f,$15,$83,$00,$85
	.byte $6c,$60,$28,$5f,$10,$83,$6c,$60,$28,$5f,$13,$83,$00,$83,$00,$6c
	.byte $60,$28,$5f,$15,$83
@ref320:
	.byte $6c,$30,$87,$00,$8d,$6c,$60,$28,$5f,$04,$83,$6c,$60,$28,$5f,$15
	.byte $83,$6c,$60,$28,$5f,$0d,$83,$0e,$85,$6c,$60,$28,$5f,$0f,$83
	.byte $ff,$05
	.word @ref313
	.byte $ff,$0e
	.word @ref318
	.byte $ff,$16
	.word @ref319
	.byte $ff,$11
	.word @ref320
	.byte $ff,$05
	.word @ref313
	.byte $ff,$0e
	.word @ref318
	.byte $ff,$16
	.word @ref315
@ref328:
	.byte $6c,$60,$2e,$00,$83,$6c,$60,$28,$00,$8b,$6c,$60,$23,$00,$8b,$6c
	.byte $10,$3c,$85,$6c,$10,$36,$85,$6c,$10,$2e,$85
	.byte $fd
	.word @song2ch2loop

; sewer
@song2ch3:
@song2ch3loop:
@ref329:
	.byte $74,$8a,$0c,$85,$72,$9c,$0c,$85,$74,$8a,$0c,$85,$72,$9c,$0c,$85
	.byte $74,$82,$06,$73,$81,$72,$81,$71,$89,$74,$9c,$0c,$85,$72,$0c,$85
@ref330:
	.byte $74,$94,$0f,$73,$81,$72,$81,$71,$81,$70,$87,$74,$9c,$0c,$8d,$74
	.byte $82,$06,$73,$81,$72,$81,$71,$89,$74,$8a,$0c,$85,$72,$9c,$0c,$85
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
	.byte $ff,$10
	.word @ref329
	.byte $ff,$0f
	.word @ref330
@ref345:
	.byte $76,$88,$0a,$8b,$00,$73,$0a,$8b,$00,$71,$0a,$8b,$00,$71,$0a,$85
	.byte $72,$8a,$0c,$81,$72,$0c,$81
@ref346:
	.byte $73,$82,$06,$72,$81,$71,$81,$70,$81,$73,$05,$72,$81,$71,$81,$70
	.byte $89,$73,$05,$72,$81,$71,$81,$70,$a1
	.byte $fd
	.word @song2ch3loop

; sewer
@song2ch4:
@song2ch4loop:
@ref347:
	.byte $bf
@ref348:
	.byte $bf
@ref349:
	.byte $bf
@ref350:
	.byte $bf
@ref351:
	.byte $bf
@ref352:
	.byte $bf
@ref353:
	.byte $bf
@ref354:
	.byte $bf
@ref355:
	.byte $bf
@ref356:
	.byte $bf
@ref357:
	.byte $bf
@ref358:
	.byte $bf
@ref359:
	.byte $bf
@ref360:
	.byte $bf
@ref361:
	.byte $bf
@ref362:
	.byte $bf
@ref363:
	.byte $bf
@ref364:
	.byte $bf
	.byte $fd
	.word @song2ch4loop
