;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


songs_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,389,324 ; title

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env7
	.word @env4,@env0,@env0,@env0
	.word @env5,@env0,@env0,@env0
	.word @env3,@env6,@env0,@env9
	.word @env3,@env0,@env0,@env10
	.word @env4,@env0,@env0,@env7
	.word @env5,@env0,@env0,@env8
	.word @env3,@env0,@env0,@env7

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c7,$c7,$c6,$c6,$c5,$02,$c4
	.byte $c4,$c3,$02,$c2,$02,$c1,$04,$c0,$c0,$c0,$00,$19
@env2:
	.byte $cf,$cf,$cd,$03,$cc,$04,$cb,$03,$ca,$04,$c9,$03,$c8,$05,$c7,$05
	.byte $c6,$05,$c5,$06,$c4,$07,$c3,$08,$c2,$09,$c1,$0b,$c0,$02,$c0,$00
	.byte $1e
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $cc,$ca,$c8,$c6,$ca,$c7,$c5,$c4,$c3,$c2,$c1,$c0,$c0,$00,$0c
@env5:
	.byte $cf,$cb,$c6,$c2,$c0,$00,$04
@env6:
	.byte $d8,$d8,$d3,$d3,$d0,$d0,$ce,$ce,$cc,$cc,$c7,$c7,$c4,$c4,$c2,$c2
	.byte $c0,$c0,$00,$00
@env7:
	.byte $c2,$00,$00
@env8:
	.byte $c1,$00,$00
@env9:
	.byte $c2,$c1,$c3,$00,$02
@env10:
	.byte $c3,$00,$00


; title
@song0ch0:
	.byte $fb,$02
@ref0:
	.byte $8f
@ref1:
	.byte $8f
@song0ch0loop:
@ref2:
	.byte $7a,$82,$04,$ad,$6c,$0a,$8f
@ref3:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$85,$00,$85
@ref4:
	.byte $7a,$04,$85,$00,$85,$04,$ad
@ref5:
	.byte $6c,$0a,$8f,$5f,$00,$9d,$04,$83,$00,$04,$83,$00
@ref6:
	.byte $7a,$04,$ad,$6c,$0a,$8f
@ref7:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$83,$00,$04,$83,$00
	.byte $ff,$06
	.word @ref4
@ref9:
	.byte $6c,$0a,$8f,$5f,$00,$8d,$0b,$9d
	.byte $ff,$03
	.word @ref6
@ref11:
	.byte $5f,$00,$8d,$04,$8d,$00,$8d,$04,$83,$00,$7c,$04,$83,$00
@ref12:
	.byte $7a,$04,$85,$00,$85,$7a,$04,$9b,$00,$04,$8b,$00
@ref13:
	.byte $03,$b3,$00,$03,$83,$00
@ref14:
	.byte $7a,$01,$9d,$7a,$0d,$9d
@ref15:
	.byte $7a,$09,$9d,$7a,$10,$9d
@ref16:
	.byte $7a,$0e,$85,$00,$85,$7a,$0e,$9d,$7a,$09,$8d
@ref17:
	.byte $7a,$06,$9b,$00,$02,$9d
@ref18:
	.byte $78,$8a,$1f,$8f,$72,$8d,$7a,$8c,$18,$19,$1a,$99
@ref19:
	.byte $1f,$95,$6c,$09,$85,$00,$5f,$25,$26,$99,$00
@ref20:
	.byte $7a,$25,$9d,$66,$8d,$00,$60,$21,$8b,$00
@ref21:
	.byte $60,$1f,$20,$21,$b7,$00
@ref22:
	.byte $77,$8a,$1f,$8f,$72,$8d,$7a,$8c,$18,$19,$1a,$8d,$1c,$81,$1a,$81
	.byte $19,$81
@ref23:
	.byte $1f,$95,$6c,$04,$85,$00,$5f,$22,$23,$99,$00
@ref24:
	.byte $7a,$21,$85,$1c,$83,$00,$1c,$ad
@ref25:
	.byte $66,$9d,$60,$00,$74,$8e,$31,$85,$75,$32,$85,$76,$34,$85,$77,$39
	.byte $83,$00
	.byte $ff,$0d
	.word @ref22
@ref27:
	.byte $1f,$95,$6c,$04,$85,$00,$5f,$25,$26,$99,$00
@ref28:
	.byte $25,$85,$26,$83,$00,$28,$8d,$66,$8d,$60,$00,$26,$85,$25,$83,$00
@ref29:
	.byte $26,$9d,$66,$8d,$60,$00,$21,$85,$23,$83,$00
@ref30:
	.byte $24,$9d,$66,$8d,$60,$00,$26,$85,$24,$83,$00
@ref31:
	.byte $23,$9d,$6d,$17,$1f,$9d
@ref32:
	.byte $23,$bd
@ref33:
	.byte $66,$9f,$60,$00,$83,$00,$5f,$82,$01,$83,$00,$02,$83,$00,$03,$83
	.byte $00
	.byte $fd
	.word @song0ch0loop

; title
@song0ch1:
@ref34:
	.byte $8f
@ref35:
	.byte $8f
@song0ch1loop:
@ref36:
	.byte $7a,$86,$28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85
	.byte $1e,$85
@ref37:
	.byte $28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85,$1e,$85
@ref38:
	.byte $79,$2a,$85,$25,$85,$22,$85,$20,$85,$2a,$85,$25,$85,$22,$85,$20
	.byte $85
@ref39:
	.byte $12,$85,$16,$85,$19,$85,$16,$85,$19,$85,$1e,$85,$22,$85,$25,$85
@ref40:
	.byte $79,$28,$85,$25,$85,$23,$85,$21,$85,$2d,$85,$28,$85,$25,$85,$21
	.byte $85
@ref41:
	.byte $28,$85,$24,$85,$23,$85,$21,$85,$28,$85,$24,$85,$23,$85,$21,$85
@ref42:
	.byte $79,$28,$85,$23,$85,$20,$85,$1e,$85,$28,$85,$23,$85,$20,$85,$1e
	.byte $85
@ref43:
	.byte $10,$85,$14,$85,$17,$85,$1c,$85,$17,$85,$1c,$85,$20,$85,$23,$85
	.byte $ff,$10
	.word @ref42
	.byte $ff,$10
	.word @ref37
@ref46:
	.byte $79,$2a,$85,$28,$85,$22,$85,$1e,$85,$2a,$85,$28,$85,$22,$85,$1e
	.byte $85
@ref47:
	.byte $2a,$85,$25,$85,$23,$85,$1e,$85,$2f,$85,$2a,$85,$27,$85,$23,$85
@ref48:
	.byte $79,$28,$85,$25,$85,$23,$85,$21,$85,$28,$85,$25,$85,$23,$85,$21
	.byte $85
@ref49:
	.byte $31,$85,$2f,$85,$2d,$85,$28,$85,$34,$85,$31,$85,$2f,$85,$2d,$85
@ref50:
	.byte $79,$36,$85,$34,$85,$32,$85,$2d,$85,$36,$85,$34,$85,$32,$85,$2d
	.byte $85
@ref51:
	.byte $32,$85,$2d,$85,$2a,$85,$2d,$85,$2a,$85,$26,$85,$2a,$85,$2d,$85
@ref52:
	.byte $79,$2f,$85,$2d,$85,$2b,$85,$26,$85,$8e,$2f,$85,$2d,$85,$2b,$85
	.byte $26,$85
@ref53:
	.byte $86,$2f,$85,$2d,$85,$2b,$85,$26,$85,$8e,$2f,$85,$2d,$85,$2b,$85
	.byte $26,$85
@ref54:
	.byte $79,$86,$31,$85,$2f,$85,$2d,$85,$28,$85,$8e,$31,$85,$2f,$85,$2d
	.byte $85,$28,$85
@ref55:
	.byte $86,$31,$85,$2f,$85,$2d,$85,$28,$85,$8e,$31,$85,$2f,$85,$2d,$85
	.byte $28,$85
@ref56:
	.byte $79,$86,$2f,$85,$2d,$85,$2b,$85,$26,$85,$8e,$2f,$85,$2d,$85,$2b
	.byte $85,$26,$85
	.byte $ff,$10
	.word @ref53
@ref58:
	.byte $79,$86,$28,$85,$25,$85,$23,$85,$1c,$85,$8e,$31,$85,$2f,$85,$2d
	.byte $85,$28,$85
@ref59:
	.byte $86,$25,$85,$28,$85,$2d,$85,$28,$85,$8e,$2d,$85,$2f,$85,$31,$85
	.byte $34,$85
	.byte $ff,$10
	.word @ref56
	.byte $ff,$10
	.word @ref53
	.byte $ff,$10
	.word @ref54
@ref63:
	.byte $86,$32,$85,$2d,$85,$2a,$85,$28,$85,$26,$85,$21,$85,$26,$85,$8e
	.byte $26,$85
@ref64:
	.byte $79,$86,$2b,$85,$28,$85,$24,$85,$1f,$85,$8e,$28,$85,$24,$85,$1f
	.byte $85,$1c,$85
@ref65:
	.byte $79,$86,$2b,$85,$26,$85,$23,$85,$1f,$85,$8e,$26,$85,$23,$85,$1f
	.byte $85,$1a,$85
@ref66:
	.byte $79,$86,$28,$85,$25,$85,$23,$85,$1e,$85,$79,$28,$85,$25,$85,$23
	.byte $85,$1e,$85
@ref67:
	.byte $79,$28,$85,$25,$85,$23,$85,$1e,$85,$2a,$85,$27,$85,$23,$85,$21
	.byte $85
	.byte $fd
	.word @song0ch1loop

; title
@song0ch2:
@ref68:
	.byte $8f
@ref69:
	.byte $8f
@song0ch2loop:
@ref70:
	.byte $9f,$84,$2d,$2e,$2f,$97,$00
@ref71:
	.byte $34,$95,$6c,$04,$85,$00,$5f,$3a,$3b,$99,$00
@ref72:
	.byte $3a,$bd
@ref73:
	.byte $63,$9f,$60,$00,$8d,$36,$85,$38,$83,$00
@ref74:
	.byte $39,$9d,$63,$9d,$00
@ref75:
	.byte $60,$3b,$9d,$63,$97,$60,$39,$83,$00
@ref76:
	.byte $38,$85,$36,$83,$00,$34,$9d,$63,$8f
@ref77:
	.byte $8f,$60,$00,$ad
@ref78:
	.byte $9f,$2d,$2e,$2f,$8d,$31,$81,$2f,$81,$2e,$81
	.byte $ff,$08
	.word @ref71
@ref80:
	.byte $3d,$9d,$63,$8d,$60,$00,$3b,$85,$3a,$83,$00
@ref81:
	.byte $3b,$9d,$00,$8d,$36,$85,$38,$83,$00
@ref82:
	.byte $39,$9d,$63,$8d,$00,$60,$38,$85,$36,$83,$00
@ref83:
	.byte $34,$95,$6c,$05,$87,$5f,$31,$8d,$36,$8d
@ref84:
	.byte $36,$bd
@ref85:
	.byte $63,$9f,$60,$00,$9d
@ref86:
	.byte $82,$13,$85,$00,$85,$13,$85,$00,$a5
@ref87:
	.byte $8f,$13,$8d,$00,$8d,$13,$83,$00,$13,$83,$00
@ref88:
	.byte $13,$85,$00,$85,$13,$85,$00,$a5
@ref89:
	.byte $97,$92,$00,$85,$82,$0e,$95,$92,$00,$85
	.byte $ff,$08
	.word @ref86
	.byte $ff,$0b
	.word @ref87
	.byte $ff,$08
	.word @ref88
@ref93:
	.byte $8f,$0e,$8d,$00,$8d,$0e,$8d
	.byte $ff,$08
	.word @ref88
	.byte $ff,$0b
	.word @ref87
@ref96:
	.byte $15,$9d,$6d,$20,$21,$9d
@ref97:
	.byte $5f,$1e,$9d,$0e,$9b,$00
@ref98:
	.byte $10,$bd
@ref99:
	.byte $5f,$13,$9d,$5f,$1a,$9b,$00
@ref100:
	.byte $1e,$ab,$00,$8e,$19,$83,$00,$17,$83,$00
@ref101:
	.byte $82,$12,$9b,$00,$17,$9b,$00
	.byte $fd
	.word @song0ch2loop

; title
@song0ch3:
@ref102:
	.byte $74,$80,$0c,$85,$76,$0a,$85
@ref103:
	.byte $78,$07,$85,$7a,$05,$85
@song0ch3loop:
@ref104:
	.byte $76,$82,$0a,$85,$75,$87,$74,$85,$72,$85,$71,$83,$00,$8d,$73,$88
	.byte $0e,$81,$74,$0e,$81,$75,$0e,$81,$76,$0e,$81
@ref105:
	.byte $77,$80,$06,$75,$81,$73,$81,$71,$81,$00,$85,$73,$82,$06,$85,$72
	.byte $87,$71,$81,$00,$8b,$75,$88,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78
	.byte $0e,$81
@ref106:
	.byte $77,$0e,$85,$74,$0e,$85,$75,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$85,$74,$0e,$85
@ref107:
	.byte $78,$82,$0f,$85,$75,$87,$72,$83,$71,$83,$72,$88,$0e,$85,$74,$80
	.byte $0c,$85,$74,$0a,$85,$74,$08,$85,$74,$07,$85
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
	.byte $ff,$10
	.word @ref104
	.byte $ff,$14
	.word @ref105
	.byte $ff,$10
	.word @ref106
	.byte $ff,$0f
	.word @ref107
@ref120:
	.byte $7a,$90,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85
	.byte $74,$0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
@ref121:
	.byte $7a,$88,$06,$78,$81,$76,$81,$73,$81,$00,$85,$7a,$0f,$85,$78,$87
	.byte $77,$90,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85
@ref122:
	.byte $7a,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
@ref126:
	.byte $77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74,$0e,$85,$77,$0e,$85,$74
	.byte $0e,$85,$75,$0e,$81,$76,$0e,$81,$77,$0e,$81,$78,$0e,$81
@ref127:
	.byte $7a,$88,$06,$78,$81,$76,$81,$73,$81,$00,$85,$75,$90,$0e,$81,$76
	.byte $0e,$81,$77,$0e,$81,$78,$0e,$81,$7a,$88,$06,$78,$81,$76,$81,$73
	.byte $81,$74,$90,$0e,$85,$7a,$0f,$85,$78,$87
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref122
	.byte $ff,$11
	.word @ref121
	.byte $ff,$14
	.word @ref126
@ref135:
	.byte $7a,$06,$78,$81,$76,$81,$73,$81,$00,$85,$7a,$0f,$85,$78,$87,$72
	.byte $80,$0c,$85,$73,$0a,$85,$74,$07,$85,$77,$05,$85
	.byte $fd
	.word @song0ch3loop

; title
@song0ch4:
@ref136:
	.byte $8f
@ref137:
	.byte $8f
@song0ch4loop:
@ref138:
	.byte $bf
@ref139:
	.byte $bf
@ref140:
	.byte $bf
@ref141:
	.byte $bf
@ref142:
	.byte $bf
@ref143:
	.byte $bf
@ref144:
	.byte $bf
@ref145:
	.byte $bf
@ref146:
	.byte $bf
@ref147:
	.byte $bf
@ref148:
	.byte $bf
@ref149:
	.byte $bf
@ref150:
	.byte $bf
@ref151:
	.byte $bf
@ref152:
	.byte $bf
@ref153:
	.byte $bf
@ref154:
	.byte $bf
@ref155:
	.byte $bf
@ref156:
	.byte $bf
@ref157:
	.byte $bf
@ref158:
	.byte $bf
@ref159:
	.byte $bf
@ref160:
	.byte $bf
@ref161:
	.byte $bf
@ref162:
	.byte $bf
@ref163:
	.byte $bf
@ref164:
	.byte $bf
@ref165:
	.byte $bf
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@ref168:
	.byte $bf
@ref169:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
